openapi: 3.0.0
x-stoplight:
  id: 889lpyh25kpg8
info:
  title: GeoHub Static Image API
  version: '1.0'
  summary: GeoHub Static Image API Spec
  description: This documentation describes GeoHub Static Image API Spec.
servers:
  - url: /api
    description: Static Image API
paths:
  '/bounds/{lon},{lat},{zoom}/{width}x{height}':
    parameters:
      - $ref: '#/components/parameters/lon'
      - $ref: '#/components/parameters/lat'
      - $ref: '#/components/parameters/zoom'
      - $ref: '#/components/parameters/width'
      - $ref: '#/components/parameters/height'
    get:
      summary: Get bounds from center and zoom
      tags:
        - bounds
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  bounds:
                    type: array
                    items:
                      type: number
                required:
                  - bounds
              examples:
                Example:
                  value:
                    bounds:
                      - -210.9375
                      - -80.17871349622823
                      - 210.9375
                      - 80.17871349622823
      operationId: 'get-bounds-lon-,-lat-,-zoom-width-x-height'
      description: Get bounds from center and zoom
  '/style/static/{bbox}/{width}x{height}.png':
    parameters:
      - $ref: '#/components/parameters/bbox'
      - $ref: '#/components/parameters/width'
      - $ref: '#/components/parameters/height'
    get:
      summary: Static image by bbox
      tags:
        - static image
      responses:
        '200':
          description: OK
          headers: {}
      operationId: get-style-static-bbox-width-x-height-.png
      description: get static image by BBOX
      parameters:
        - $ref: '#/components/parameters/url'
  '/style/static/{bbox}/{width}x{height}.png@2x':
    parameters:
      - $ref: '#/components/parameters/bbox'
      - $ref: '#/components/parameters/width'
      - $ref: '#/components/parameters/height'
    get:
      summary: Static image @2x by bbox
      tags:
        - static image
      responses:
        '200':
          description: OK
          headers: {}
      operationId: get-style-static-bbox-width-x-height-.png
      description: get static image @2x by BBOX
      parameters:
        - $ref: '#/components/parameters/url'
  '/style/static/{lon},{lat},{zoom},{bearing},{pitch}/{width}x{height}.png':
    parameters:
      - $ref: '#/components/parameters/lon'
      - $ref: '#/components/parameters/lat'
      - $ref: '#/components/parameters/zoom'
      - $ref: '#/components/parameters/bearing'
      - $ref: '#/components/parameters/pitch'
      - $ref: '#/components/parameters/width'
      - $ref: '#/components/parameters/height'
    get:
      summary: Static image by center and zoom
      tags:
        - static image
      responses:
        '200':
          description: OK
      operationId: 'get-style-static-lon-,-lat-,-zoom-,-bearing-,-pitch-width-x-height-.png'
      parameters:
        - $ref: '#/components/parameters/url'
      description: get static image by center and zoom
  '/style/static/{lon},{lat},{zoom},{bearing},{pitch}/{width}x{height}.png@2x':
    parameters:
      - $ref: '#/components/parameters/lon'
      - $ref: '#/components/parameters/lat'
      - $ref: '#/components/parameters/zoom'
      - $ref: '#/components/parameters/bearing'
      - $ref: '#/components/parameters/pitch'
      - $ref: '#/components/parameters/width'
      - $ref: '#/components/parameters/height'
    get:
      summary: Static image @2x by center and zoom
      tags:
        - static image
      responses:
        '200':
          description: OK
      operationId: 'get-style-static-lon-,-lat-,-zoom-,-bearing-,-pitch-width-x-height-.png'
      parameters:
        - $ref: '#/components/parameters/url'
      description: get static image @2x by center and zoom
  '/style/static/auto/{width}x{height}.png':
    parameters:
      - name: width
        in: path
        required: true
        schema:
          type: integer
          default: 300
        description: image width (pixel)
      - name: height
        in: path
        required: true
        schema:
          type: number
          default: 200
        description: image height (pixel)
    get:
      summary: Static image with default location
      tags:
        - static image
      responses:
        '200':
          description: OK
      operationId: get-style-static-auto-width-x-height-.png
      description: get static image by default location in style.json automatically
      parameters:
        - $ref: '#/components/parameters/url'
  '/style/static/auto/{width}x{height}.png@2x':
    parameters:
      - name: width
        in: path
        required: true
        schema:
          type: integer
          default: 300
        description: image width (pixel)
      - name: height
        in: path
        required: true
        schema:
          type: number
          default: 200
        description: image height (pixel)
    get:
      summary: Static image @2x with default location
      tags:
        - static image
      responses:
        '200':
          description: OK
      operationId: get-style-static-auto-width-x-height-.png
      description: get static image @2x by default location in style.json automatically
      parameters:
        - $ref: '#/components/parameters/url'
components:
  schemas: {}
  parameters:
    lon:
      name: lon
      in: path
      required: true
      schema:
        type: number
        default: 0
      description: longitude
    lat:
      name: lat
      in: path
      required: true
      schema:
        type: number
        default: 0
      description: latitude
    zoom:
      name: zoom
      in: path
      required: true
      schema:
        type: number
        default: 0
        minimum: 0
        maximum: 22
      description: zoom level
    width:
      name: width
      in: path
      required: true
      schema:
        type: integer
        default: 300
      description: image width (pixel)
    height:
      name: height
      in: path
      required: true
      schema:
        type: number
        default: 200
      description: image height (pixel)
    bbox:
      name: bbox
      in: path
      required: true
      schema:
        type: string
        example: '-4.04296875,-15.114552871944102,48.69140625,19.476950206488414'
      description: 'bbox (minx, miny, maxx, maxy)'
    url:
      name: url
      in: query
      required: true
      schema:
        type: string
        example: 'https://unpkg.com/@undp-data/style@latest/dist/style.json'
      description: URL of style.json
    bearing:
      name: bearing
      in: path
      required: true
      schema:
        type: number
        default: 0
      description: bearing
    pitch:
      name: pitch
      in: path
      required: true
      schema:
        type: number
        default: 0
    retina:
      name: retina
      in: path
      schema:
        type: string
        example: '@2x'
      description: '@2x'
