# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CI: true
  AZURE_STATIC_WEB_APP_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APP_API_TOKEN }}
  SWA_APP_NAME: maplibre-static-image-api

jobs:
  build_and_deploy_job:
    name: Build and deploy Azure Static Web App
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies for maplibre-gl-native
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ccache \
            cmake \
            ninja-build \
            pkg-config \
            xvfb \
            libcurl4-openssl-dev \
            libglfw3-dev \
            libuv1-dev \
            g++-10 \
            libc++-9-dev \
            libc++abi-9-dev \
            libjpeg-dev \
            libpng-dev \
            libwebp-dev
          /usr/sbin/update-ccache-symlinks

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: deploy
        if: ${{ github.ref == 'refs/heads/main'}}
        run: |
          npx swa deploy ./build --api-location ./build/server --app-name ${{env.SWA_APP_NAME}} --deployment-token ${{env.AZURE_STATIC_WEB_APP_API_TOKEN}}
